# Explicación númerica de MLP

Tarea solucionada por : Laura Sofía Leyva Aldana

Presentado a : Andrés Felipe Escallón Portilla

Referencias:

*Basic numerical examples (MLP and others):

https://www.linkedin.com/posts/tom-yeh_deeplearning-llms-generativeai-activity-7161408843111956480-ujq0/


- Perceptron:

https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-activity-7171891528448008192-nulK/?utm_source=share&utm_medium=member_android

- Video about MLP numerical operation:

https://www.linkedin.com/posts/annarahn_deeplearning-neuralnetworks-math-ugcPost-7171662948967411712-ZIEx?utm_source=share&utm_medium=member_android


*Other:

- https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-ugcPost-7174203548736319488-RM0S?utm_source=share&utm_medium=member_android


- https://alfanotv.com/raspberry-pi/como-multiplicar-matrices-en-numpy-multiply-matmul/



In [50]:
import numpy as np

array_1 = np.array([[1, 1],[-1,1]])


W = np.array(     [ [1, 1], [-1,1] ]   )
print("\n W = \n", W)
#print()


array_2 = np.array ([[1, 5, 2],[2, 4, 2]])

X = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )
print("\n X = \n",X)
#print()

WX_1 = np.dot(W,X)
print("\n WX_1 = \n",WX_1)
#print()

WX_2 = np.matmul(W,X)
print("\n WX_2 = \n",WX_2)
#print()

#XW = np.matmul(X,W)
#print(XW)
#print()
# Lo anterior no funciona por lo siguiente:
#X_(2,3) por W_(2,2) = Resultado_(2,2)?
#porque el numero de columnas de X es diferente al numero de filas de W


 W = 
 [[ 1  1]
 [-1  1]]

 X = 
 [[1 5 2]
 [2 4 2]]

 WX_1 = 
 [[ 3  9  4]
 [ 1 -1  0]]

 WX_2 = 
 [[ 3  9  4]
 [ 1 -1  0]]



```
W_(2,2) por X_(2,3) = WX_(2,3)

W*x + b = Z ---> Activation = output

W_(3,4) por x_(4,5) = Z_(3,5)

Asumiendo que todos los biases son cero y que NO hay función de activación (es decir: se deja pasar la misma información)

```


In [51]:
W = np.array([   [1,1,0,-1], [-1,1,2,-3], [-1,1,5,0]  ])
print(W)

print()

x = np.array([ [1,5,2,-1,0], [2,4,2,1,-1], [7,5,6,-1,1], [-8,0,4,-1,3] ])
print(x)
print()

b = np.zeros((3, 5)) # suponer todos los valores de los biases en cero
print(b)
print()

Z = np.matmul(W,x) + b
print(Z)

[[ 1  1  0 -1]
 [-1  1  2 -3]
 [-1  1  5  0]]

[[ 1  5  2 -1  0]
 [ 2  4  2  1 -1]
 [ 7  5  6 -1  1]
 [-8  0  4 -1  3]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[11.  9.  0.  1. -4.]
 [39.  9.  0.  3. -8.]
 [36. 24. 30. -3.  4.]]


# Explicación manual:

```
W =
[[ 1  1]
 [-1  1]]

x=
 [[1 5 2]
 [2 4 2]]

Entonces:

W*x + b:

b=zeros
W*x  + 0 = W*x = Z
[[ 3  9  4]
 [ 1 -1  0]]

Z-->relu-->A
A=
[[ 3  9  4]
 [ 1  0  0]]

===============
W*x =
[[ 3  9  4]
 [ 1 -1  0]]

+ b (b=ones)
W*x + b:
[[ 4  10  5]
 [ 2  0   1]]

W*x + b = Z
Z-->relu-->A

A=
[[ 4  10  5]
 [ 2  0   0]]

=========================

Comparar el resultado conocido (Supervisado)
Supongamos que el resultado conocido es:
Y_real=
[[ 4  10  5]
 [ 2  0   0]]
y sucedió que la red calculó y dio:
A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ 0  0  0]
 [ 0  0   0]]

===============================================
O supongamos que el resultado conocido debe ser:
Y_real=
[[ -3  6  2]
 [ 0   5 -1]]
y sucedió que la red calculó y dio:

A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ -7  -4  -3]
 [ -2  5   -1]]


```






# Operaciones correctas vs incorrectas:

## Si no se cumple lo dicho incialmente, entonces no se puede multiplicar matrices desde el procedimiento de algebra lineal:

## "*" y multiply son para multiplicar elemento a elemento matrices del mismo tamaño = num_filas x num_columnas

In [52]:
#array_r_bad1 = array_1 * array_2
#print(array_r_bad1)

np.array([1,1])*np.array([1,1])

array([1, 1])

In [53]:
print(np.array([2,4])*np.array([3,-5]))

[  6 -20]


In [54]:
np.multiply(np.array([2,4]), np.array([3,-5]))

array([  6, -20])

In [55]:
array_new_1 = np.array([[1, 1,1],[-1,1,1]])
array_new_2 = np.array ([[1, 5, 2],[2, 4, 2]])

array_r = np.dot(array_new_2,array_new_1.T)
print(array_r)

[[8 6]
 [8 4]]


In [56]:
mult3 = np.multiply(array_new_1,array_new_2)
print(mult3)

[[ 1  5  2]
 [-2  4  2]]


# HOMEWORK:

# Ejemplo académico:

Definiendo funciones en python para calcular:

 W x + b = Z --> relu ---> y

In [57]:
def get_output_from_MLP_input(W,x,b,activation="linear"):
  #print("W = ",end='\n')
  #print(W)
  print(f"W = \n {W} \n")
  #print()

  print("x = ",end='\n')
  print(x)
  print("b = ",end='\n')
  print(b)
  # arguments:
  # W,x and b are arrays

  # operations
  # Z = W x  +  b
  #Z = np.matmul(W,x) + b
  Z = np.dot(W,x) + b

  print("Z = ",end='\n')
  print(Z)

  if activation=="linear":
    y = Z

  if activation=="relu":
    # Ternary operator to define a relu function
    #y = Z if Z>=0 else 0
    #y = Z if Z>0 else 0
    #y = 0 if Z<0 else Z
    #y = 0 if Z<=0 else Z
    y = np.array([0 if z<=0 else z for z in Z])

  #TO-DO:
  #Funciones de activación

  if activation=="sigmoid":
    y = (1 / (1 + np.exp(-x)))

  if activation=="tanh":
    y = ((np.exp(Z)-np.exp(-Z))/(np.exp(Z)+np.exp(-Z)))

  if activation=="arctanh":
    tan = ((np.exp(Z)-np.exp(-Z))/(np.exp(Z)+np.exp(-Z)))
    y = tan**(-1)

  if activation=="softmax":
    y = np.exp(Z)/np.sum(np.exp(Z))

  if activation=="leakyRelu":
    alpha=0.01
    y = [z if z >= 0 else alpha * z for z in Z]

  if activation=="maxout":
    y = np.array([max(0,z) for z in Z])

  if activation=="PReLU":
    a=0.01
    y =  np.array([max(a*z,z) for z in Z])

  if activation=="ELU":
    alpha=0.01
    y = [z if z >= 0 else  alpha*(np.exp(z)-1) for z in Z]

  if activation=="softplus":
    y = np.log(1+np.exp(Z))


  print("y = ",end='\n')
  print(y)

  return y

In [58]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b, activation="linear")
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1  3  5  3]


array([-1,  3,  5,  3])

In [59]:
# Testing (relu)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"relu")
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0 3 5 3]


array([0, 3, 5, 3])

In [60]:
# Testing (Sigmoid)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"sigmoid")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0.88079708 0.73105858 0.95257413]


In [61]:
# Testing (Tanh)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"tanh")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.76159416  0.99505475  0.9999092   0.99505475]


In [62]:
# Testing (Arctanh)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"arctanh")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1.31303529  1.00496982  1.0000908   1.00496982]


In [63]:
# Testing (Softmax)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"softmax")
sum_y=np.sum(y)
print(sum_y)

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0.00194695 0.10629962 0.78545382 0.10629962]
1.0


In [64]:
# Testing (leakyRelu)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"leakyRelu")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.01, 3, 5, 3]


In [65]:
# Testing (maxout)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"maxout")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0 3 5 3]


In [66]:
# Testing (PReLU)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"PReLU")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.01  3.    5.    3.  ]


In [67]:
# Testing (ELU)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"ELU")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.006321205588285576, 3, 5, 3]


In [68]:
# Testing (softplus)
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"softplus")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0.31326169 3.04858735 5.00671535 3.04858735]


# Ojo: la multiplicacion entre matrices en general NO es conmutativa

AB=C en general es distinto de BA=D

(suponiendo que por las dimensiones se puedan operar)

Ejemplo: al intercambiar Wx con xW hay error

In [69]:
#y = get_output_from_MLP_input(x,W,b) -> Se genera error por que la multiplicación entre matrices NO es CONMUTATIVA
y = get_output_from_MLP_input(W,x,b)

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1  3  5  3]
