Realizar convolución 1D en Python

In [ ]:
import numpy as np

# Definir las señales de entrada y el filtro

x = np.array([2, 1, 0, 1, 2]) # Señal de entrada
h = np.array([1, -1]) # Filtro

# Realizar la convolución

y = np.convolve(x, h, mode='valid')

# Imprimir el resultado

print("Señal de salida después de la convolución:")
print(y)

Señal de salida después de la convolución:
[-1 -1  1  1]


Ejemplo númerico de convolución 2D discreto

In [ ]:
import numpy as np
from scipy.signal import convolve2d
# Definir la matriz de entrada (señal) y el kernel
input_matrix = np.array([[1, 2, 3, 3],
                         [4, 5, 6, 6],
                         [7, 8, 9, 9],
                         [7, 8, 9, 9]])
kernel = np.array([[0, 1, 0],
                   [-1, 1,-1],
                   [0, 1, 0]])

# Realizar 1a convolución 2D con mode - valid
output_matrix_c_mode = convolve2d(input_matrix, kernel, mode='valid')
print("Matriz de salida después de la convolución con mode valid:")
print(output_matrix_c_mode)

# Realizar 1a convolución 2D sin mode -valid
output_matrix_s_mode = convolve2d(input_matrix, kernel)
print("Matriz de salida después de la convolución sin mode valid:")
print(output_matrix_s_mode)

Matriz de salida después de la convolución con mode valid:
[[5 7]
 [5 7]]
Matriz de salida después de la convolución sin mode valid:
[[ 0  1  2  3  3  0]
 [-1  3  3  4  6 -3]
 [-4  7  5  7 12 -6]
 [-7 10  5  7 15 -9]
 [-7  6  0  1  9 -9]
 [ 0  7  8  9  9  0]]
